language: node_js
node_js:
  - 13

branches:
  only:
    - master

before_install:
  - git clone https://github.com/unicode-org/cldr
  - git checkout -b updates
  - git pull

script:
  - yarn build

after_success:
  - ls
  - chmod +x ./push.sh
  - ./push.sh
  - yarn pr
