language: node_js
node_js:
  - 14
  - 13
  - 12
  - 10
  - 8

before_install:
  - git clone https://github.com/unicode-org/cldr

script:
  - yarn build
  - git add .
  - git commit -m "Build $TRAVIS_BUILD_NUMBER - Automated JSON update"
  - git push -u origin $TRAVIS_BRANCH
